<?php

namespace DevTheorem\PeachySQL\QueryBuilder;

/**
 * Class used for insert query generation
 * @psalm-type ColValues = array<string, mixed>
 */
class Insert extends Query
{
    /**
     * Returns the array of columns/values, split into groups containing the largest number of rows possible.
     * @param list<ColValues> $colVals
     * @return list<non-empty-list<ColValues>>
     */
    public static function batchRows(array $colVals, int $maxBoundParams, int $maxRows): array
    {
        $maxRowsPerQuery = count($colVals);

        if ($maxRowsPerQuery === 0) {
            return [];
        }

        if ($maxBoundParams > 0) {
            $maxRowsPerQuery = (int) floor($maxBoundParams / count($colVals[0])); // max bound params divided by params per row
        }

        if ($maxRows > 0 && $maxRowsPerQuery > $maxRows) {
            $maxRowsPerQuery = $maxRows;
        }

        /** @phpstan-ignore argument.type */
        return array_chunk($colVals, $maxRowsPerQuery);
    }

    /**
     * Generates an INSERT query with placeholders for values
     * @param list<ColValues> $colVals
     */
    public function buildQuery(string $table, array $colVals): SqlParams
    {
        $columns = $this->getEscapedColumns($colVals);
        $insert = "INSERT INTO {$table} (" . implode(', ', $columns) . ')';

        $valSetStr = ' (' . str_repeat('?,', count($columns) - 1) . '?),';
        $valStr = ' VALUES' . substr_replace(str_repeat($valSetStr, count($colVals)), '', -1); // remove trailing comma

        return new SqlParams($insert . $valStr, $this->getParams($colVals));
    }

    /**
     * Generates a PostgreSQL INSERT query which returns the ID of each row, in the order of the VALUES list.
     * An INSERT ... SELECT with ORDER BY would formally guarantee the order that serial values are assigned
     * (as with SQL Server), but parameters in a VALUES subquery are typed as text rather than being
     * coerced to the column types, which would break inserts into non-text columns.
     * @param list<ColValues> $colVals
     */
    public function buildReturningQuery(string $table, array $colVals, string $idColumn): SqlParams
    {
        $query = $this->buildQuery($table, $colVals);
        $sql = $query->sql . ' RETURNING ' . $this->quoteIdentifier($idColumn) . ' AS id';

        return new SqlParams($sql, $query->params);
    }

    /**
     * Generates a SQL Server batch which inserts the rows and selects the last identity value and affected count.
     * Unlike @@IDENTITY, SCOPE_IDENTITY() excludes identity values generated by triggers, and is
     * null rather than an error if the table has no identity column.
     * @param list<ColValues> $colVals
     */
    public function buildScopeIdentityQuery(string $table, array $colVals): SqlParams
    {
        $query = $this->buildQuery($table, $colVals);
        $sql = $query->sql . '; SELECT CAST(SCOPE_IDENTITY() AS bigint) AS id, @@ROWCOUNT AS affected';

        return new SqlParams($sql, $query->params);
    }

    /**
     * Generates a SQL Server batch which inserts the rows and selects their identity values in row order.
     * Unlike INSERT, MERGE can output columns from the source rows, so each identity value is output
     * along with the index of its row. This doesn't depend on the order that identity values are
     * assigned (which can differ from row order, e.g. with IDENTITY_INSERT), or the order of OUTPUT rows.
     * OUTPUT INTO is used since OUTPUT without INTO isn't allowed on tables with triggers.
     * The IDs are selected as a single JSON array, since with pdo_sqlsrv each fetched row
     * is slow when the statement has many bound parameters.
     * @param list<ColValues> $colVals
     */
    public function buildMergeOutputQuery(string $table, array $colVals, string $idColumn): SqlParams
    {
        $columns = $this->getEscapedColumns($colVals);
        $aliases = array_map(fn($i) => "p{$i}", array_keys($columns));
        $placeholders = str_repeat('?,', count($columns));
        $valSets = array_map(fn($i) => "({$placeholders}{$i})", array_keys($colVals));

        $sql = 'DECLARE @ids TABLE (id bigint, _rn int); '
            . "MERGE INTO {$table} USING (VALUES " . implode(', ', $valSets) . ')'
            . ' AS v (' . implode(', ', $aliases) . ', _rn) ON 1 = 0'
            . ' WHEN NOT MATCHED THEN INSERT (' . implode(', ', $columns) . ')'
            . ' VALUES (' . implode(', ', array_map(fn($a) => "v.{$a}", $aliases)) . ')'
            . ' OUTPUT inserted.' . $this->quoteIdentifier($idColumn) . ', v._rn INTO @ids;'
            . ' SELECT (SELECT id FROM @ids ORDER BY _rn FOR JSON PATH) AS ids';

        return new SqlParams($sql, $this->getParams($colVals));
    }

    /**
     * @param list<ColValues> $colVals
     * @return string[]
     */
    private function getEscapedColumns(array $colVals): array
    {
        if (!$colVals || empty($colVals[0])) {
            throw new \Exception('A valid array of columns/values to insert must be specified');
        }

        return $this->escapeColumns(array_keys($colVals[0]));
    }

    /**
     * @param list<ColValues> $colVals
     * @return list<mixed>
     */
    private function getParams(array $colVals): array
    {
        return array_merge(...array_map(array_values(...), $colVals));
    }
}
