<?php

namespace DevTheorem\PeachySQL\Test;

use DevTheorem\PeachySQL\PeachySql;
use DevTheorem\PeachySQL\Test\src\App;
use PDO;
use PHPUnit\Framework\Attributes\Group;

#[Group('pgsql')]
class PgsqlDbTest extends DbTestCase
{
    private static ?PeachySql $db = null;

    protected function getExpectedBadSyntaxCode(): int
    {
        return 7;
    }

    protected function getExpectedBadSyntaxError(): string
    {
        return 'syntax error';
    }

    protected function getExpectedBadSqlState(): string
    {
        return '42601';
    }

    protected function getIdentityColumnDefinition(): string
    {
        return 'INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
    }

    protected function getTriggerTestSql(): array
    {
        return [
            'DROP TABLE IF EXISTS TriggerTest',
            'DROP TABLE IF EXISTS TriggerAudit',
            'CREATE TABLE TriggerAudit (
                audit_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 5000) PRIMARY KEY,
                note INT NOT NULL
            )',
            'CREATE TABLE TriggerTest (id SERIAL PRIMARY KEY, name VARCHAR(50) NOT NULL)',
            'CREATE OR REPLACE FUNCTION trigger_test_audit() RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN INSERT INTO TriggerAudit (note) VALUES (NEW.id); RETURN NEW; END $$',
            'CREATE TRIGGER TriggerTestAudit AFTER INSERT ON TriggerTest FOR EACH ROW EXECUTE FUNCTION trigger_test_audit()',
        ];
    }

    public static function createConnection(): PDO
    {
        $c = App::$config;
        $dbName = getenv('POSTGRES_HOST') !== false ? 'postgres' : 'PeachySQL';

        return new PDO($c->getPgsqlDsn($dbName), $c->pgsqlUser, $c->pgsqlPassword, [
            PDO::ATTR_EMULATE_PREPARES => false,
        ]);
    }

    public static function dbProvider(): PeachySql
    {
        if (!self::$db) {
            self::$db = self::createTestTable(new PeachySql(self::createConnection()));
        }

        return self::$db;
    }

    public function testExplicitIdentityValues(): void
    {
        $db = static::dbProvider();
        $db->query('DROP TABLE IF EXISTS ExplicitIdentity');
        $db->query('CREATE TABLE ExplicitIdentity (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(50) NOT NULL)');

        $colVals = self::getShuffledIdRows(1000);
        $result = $db->insertRows('ExplicitIdentity', $colVals, idColumn: 'id');
        $this->assertSame(1, $result->queryCount);
        $this->assertSame(array_column($colVals, 'id'), $result->ids);
        $this->assertSame(1001, $db->insertRow('ExplicitIdentity', ['id' => 1001, 'name' => 'row1001'], 'id')->id);
    }

    private static function createTestTable(PeachySql $db): PeachySql
    {
        $sql = "
            CREATE TABLE Users (
                user_id SERIAL PRIMARY KEY,
                name VARCHAR(50) NOT NULL,
                dob DATE NOT NULL,
                weight REAL NOT NULL,
                is_disabled BOOLEAN NOT NULL,
                uuid bytea NULL,
                photo bytea NULL
            )";

        $db->query("DROP TABLE IF EXISTS Users");
        $db->query($sql);
        return $db;
    }
}
